name: Deployment

on:
  workflow_dispatch:

jobs:

  lint:
    runs-on: ubuntu-latest

    outputs:
      cache-hit: ${{ steps.cache-action.outputs.cache-hit }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Dependencies
        id: cache-action
        uses: ./.github/actions/cache-depen
        with:
          want-cache: "false"

      - name: Print Step Output
        run: |
          echo "Step Output = ${{ steps.cache-action.outputs.cache-hit }}"

      - name: Lint
        run: echo "Running Linter"


  test:
    runs-on: ubuntu-latest

    outputs:
      cache-hit: ${{ steps.cache-action.outputs.cache-hit }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Dependencies
        id: cache-action
        uses: ./.github/actions/cache-depen
        with:
          want-cache: "true"

      - name: Print Step Output
        run: |
          echo "Step Output = ${{ steps.cache-action.outputs.cache-hit }}"

      - name: Test
        run: echo "Running Tests"


  build:
    needs: test

    runs-on: ubuntu-latest

    outputs:
      cache-hit: ${{ steps.cache-action.outputs.cache-hit }}

    steps:
      - uses: actions/checkout@v4

      - name: Cache Dependencies
        id: cache-action
        uses: ./.github/actions/cache-depen

      - run: echo "Building Project"

      - run: mkdir dist

      - run: echo "Hello" > dist/file.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist


  deploy:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: ./dist

      - run: ls -R

      - run: echo "Deploying..."


  print-outputs:
    needs:
      - lint
      - test
      - build
      - deploy

    runs-on: ubuntu-latest

    steps:
      - name: Print Job Outputs
        run: |
          echo "=============================="
          echo "Lint Job Output"
          echo "${{ needs.lint.outputs.cache-hit }}"
          echo

          echo "Test Job Output"
          echo "${{ needs.test.outputs.cache-hit }}"
          echo

          echo "Build Job Output"
          echo "${{ needs.build.outputs.cache-hit }}"
          echo "=============================="